spring:
  neo4j:
      authentication:
          username: neo4j
          password: neo4j
      uri: bolt://moviedb:7687
logging:
    level:
        org.springframework.web: WARN
        com.example: DEBUG
server:
    port: 8080
